plugins {
    id 'java'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

// Spring Boot 실행 가능 jar (app 모듈만 bootJar 활성)
bootJar {
    enabled  = true
    archiveFileName = 'app.jar'   // 버전 무관하게 항상 app.jar로 고정
}
jar { enabled = false }

dependencies {
    implementation project(':core')
    implementation project(':module-dispatch')
    implementation project(':module-vehicle')
    implementation project(':module-delivery')
    implementation project(':module-dispatch-config')
    implementation project(':module-shipment')
    implementation project(':module-wms')
    implementation project(':module-document')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // MariaDB 드라이버
    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client:3.3.3'

    // JWT (runtime)
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
}
