-- ============================================================
--  module-wms-master: DDL (Oracle 19C 호환)
--  생성일: 2026-07-15  /  원본: 01_schema.sql (MariaDB/MySQL)
--  변환규칙:
--    CREATE TABLE IF NOT EXISTS → DECLARE/EXECUTE IMMEDIATE (ORA-955 무시)
--    VARCHAR(n)               → VARCHAR2(n CHAR)
--    INT                      → NUMBER(10)
--    DEFAULT ''               → DEFAULT ' '
--    ENGINE=InnoDB ...        → 제거
--    COMMENT '...' (인라인)  → COMMENT ON COLUMN 별도 문장
-- ============================================================

-- ── 공통코드 마스터 (CMCDM) ────────────────────────────────
DECLARE
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE CMCDM (
            CMCDKY  VARCHAR2(30  CHAR) NOT NULL,
            SHORTX  VARCHAR2(50  CHAR) DEFAULT '' '',
            DBFILD  VARCHAR2(50  CHAR) DEFAULT '' '',
            USARL1  VARCHAR2(100 CHAR) DEFAULT '' '',
            USARL2  VARCHAR2(100 CHAR) DEFAULT '' '',
            USARL3  VARCHAR2(100 CHAR) DEFAULT '' '',
            USARL4  VARCHAR2(100 CHAR) DEFAULT '' '',
            USARL5  VARCHAR2(100 CHAR) DEFAULT '' '',
            SYONLY  VARCHAR2(1   CHAR) DEFAULT '' '',
            CREDAT  VARCHAR2(8   CHAR) DEFAULT '' '',
            CRETIM  VARCHAR2(6   CHAR) DEFAULT '' '',
            CREUSR  VARCHAR2(12  CHAR) DEFAULT '' '',
            LMODAT  VARCHAR2(8   CHAR) DEFAULT '' '',
            LMOTIM  VARCHAR2(6   CHAR) DEFAULT '' '',
            LMOUSR  VARCHAR2(12  CHAR) DEFAULT '' '',
            INDBZL  VARCHAR2(1   CHAR) DEFAULT '' '',
            INDARC  VARCHAR2(1   CHAR) DEFAULT '' '',
            UPDCHK  NUMBER(10)         DEFAULT 0,
            CONSTRAINT PK_CMCDM PRIMARY KEY (CMCDKY)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE  CMCDM           IS '공통코드 마스터';
COMMENT ON COLUMN CMCDM.CMCDKY   IS '코드키';
COMMENT ON COLUMN CMCDM.SHORTX   IS '코드명(축약)';
COMMENT ON COLUMN CMCDM.DBFILD   IS 'DB 필드명';
COMMENT ON COLUMN CMCDM.USARL1   IS '사용처1';
COMMENT ON COLUMN CMCDM.USARL2   IS '사용처2';
COMMENT ON COLUMN CMCDM.USARL3   IS '사용처3';
COMMENT ON COLUMN CMCDM.USARL4   IS '사용처4';
COMMENT ON COLUMN CMCDM.USARL5   IS '사용처5';
COMMENT ON COLUMN CMCDM.SYONLY   IS '시스템전용';
COMMENT ON COLUMN CMCDM.CREDAT   IS '생성일자';
COMMENT ON COLUMN CMCDM.CRETIM   IS '생성시간';
COMMENT ON COLUMN CMCDM.CREUSR   IS '생성자';
COMMENT ON COLUMN CMCDM.LMODAT   IS '수정일자';
COMMENT ON COLUMN CMCDM.LMOTIM   IS '수정시간';
COMMENT ON COLUMN CMCDM.LMOUSR   IS '수정자';
COMMENT ON COLUMN CMCDM.INDBZL   IS '삭제플래그';
COMMENT ON COLUMN CMCDM.INDARC   IS '아카이브플래그';
COMMENT ON COLUMN CMCDM.UPDCHK   IS '변경카운터';


-- ── 공통코드 값 (CMCDV) ─────────────────────────────────────
DECLARE
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE CMCDV (
            CMCDKY  VARCHAR2(30  CHAR) NOT NULL,
            CMCDVL  VARCHAR2(30  CHAR) NOT NULL,
            CDESC1  VARCHAR2(100 CHAR) DEFAULT '' '',
            CDESC2  VARCHAR2(100 CHAR) DEFAULT '' '',
            USARG1  VARCHAR2(100 CHAR) DEFAULT '' '',
            USARG2  VARCHAR2(100 CHAR) DEFAULT '' '',
            USARG3  VARCHAR2(100 CHAR) DEFAULT '' '',
            USARG4  VARCHAR2(100 CHAR) DEFAULT '' '',
            USARG5  VARCHAR2(100 CHAR) DEFAULT '' '',
            CREDAT  VARCHAR2(8   CHAR) DEFAULT '' '',
            CRETIM  VARCHAR2(6   CHAR) DEFAULT '' '',
            CREUSR  VARCHAR2(12  CHAR) DEFAULT '' '',
            LMODAT  VARCHAR2(8   CHAR) DEFAULT '' '',
            LMOTIM  VARCHAR2(6   CHAR) DEFAULT '' '',
            LMOUSR  VARCHAR2(12  CHAR) DEFAULT '' '',
            INDBZL  VARCHAR2(1   CHAR) DEFAULT '' '',
            INDARC  VARCHAR2(1   CHAR) DEFAULT '' '',
            UPDCHK  NUMBER(10)         DEFAULT 0,
            CONSTRAINT PK_CMCDV PRIMARY KEY (CMCDKY, CMCDVL),
            CONSTRAINT FK_CMCDV_CMCDM FOREIGN KEY (CMCDKY) REFERENCES CMCDM(CMCDKY)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE  CMCDV           IS '공통코드 값';
COMMENT ON COLUMN CMCDV.CMCDKY   IS '코드키 (FK)';
COMMENT ON COLUMN CMCDV.CMCDVL   IS '코드값';
COMMENT ON COLUMN CMCDV.CDESC1   IS '설명1';
COMMENT ON COLUMN CMCDV.CDESC2   IS '설명2';
COMMENT ON COLUMN CMCDV.USARG1   IS '사용인수1';
COMMENT ON COLUMN CMCDV.USARG2   IS '사용인수2';
COMMENT ON COLUMN CMCDV.USARG3   IS '사용인수3';
COMMENT ON COLUMN CMCDV.USARG4   IS '사용인수4';
COMMENT ON COLUMN CMCDV.USARG5   IS '사용인수5';
COMMENT ON COLUMN CMCDV.CREDAT   IS '생성일자';
COMMENT ON COLUMN CMCDV.CRETIM   IS '생성시간';
COMMENT ON COLUMN CMCDV.CREUSR   IS '생성자';
COMMENT ON COLUMN CMCDV.LMODAT   IS '수정일자';
COMMENT ON COLUMN CMCDV.LMOTIM   IS '수정시간';
COMMENT ON COLUMN CMCDV.LMOUSR   IS '수정자';
COMMENT ON COLUMN CMCDV.INDBZL   IS '삭제플래그';
COMMENT ON COLUMN CMCDV.INDARC   IS '아카이브플래그';
COMMENT ON COLUMN CMCDV.UPDCHK   IS '변경카운터';


-- ── 물류센터(창고) 마스터 (WAHMA) ──────────────────────────
DECLARE
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE WAHMA (
            WAREKY  VARCHAR2(10  CHAR) NOT NULL,
            COMPKY  VARCHAR2(10  CHAR) DEFAULT '' '',
            TSPKEY  VARCHAR2(10  CHAR) DEFAULT '' '',
            DELMAK  VARCHAR2(1   CHAR) DEFAULT '' '',
            CHKSHA  VARCHAR2(1   CHAR) DEFAULT '' '',
            NAME01  VARCHAR2(100 CHAR) DEFAULT '' '',
            NAME02  VARCHAR2(100 CHAR) DEFAULT '' '',
            NAME03  VARCHAR2(100 CHAR) DEFAULT '' '',
            ADDR01  VARCHAR2(100 CHAR) DEFAULT '' '',
            ADDR02  VARCHAR2(100 CHAR) DEFAULT '' '',
            ADDR03  VARCHAR2(100 CHAR) DEFAULT '' '',
            ADDR04  VARCHAR2(100 CHAR) DEFAULT '' '',
            ADDR05  VARCHAR2(100 CHAR) DEFAULT '' '',
            CITY01  VARCHAR2(50  CHAR) DEFAULT '' '',
            REGN01  VARCHAR2(20  CHAR) DEFAULT '' '',
            POSTCD  VARCHAR2(10  CHAR) DEFAULT '' '',
            NATNKY  VARCHAR2(3   CHAR) DEFAULT '' '',
            TELN01  VARCHAR2(20  CHAR) DEFAULT '' '',
            TELN02  VARCHAR2(20  CHAR) DEFAULT '' '',
            TELN03  VARCHAR2(20  CHAR) DEFAULT '' '',
            CREDAT  VARCHAR2(8   CHAR) DEFAULT ''00000000'',
            CRETIM  VARCHAR2(6   CHAR) DEFAULT ''000000'',
            CREUSR  VARCHAR2(12  CHAR) DEFAULT '' '',
            LMODAT  VARCHAR2(8   CHAR) DEFAULT ''00000000'',
            LMOTIM  VARCHAR2(6   CHAR) DEFAULT ''000000'',
            LMOUSR  VARCHAR2(12  CHAR) DEFAULT '' '',
            INDBZL  VARCHAR2(1   CHAR) DEFAULT '' '',
            INDARC  VARCHAR2(1   CHAR) DEFAULT '' '',
            UPDCHK  NUMBER(10)         DEFAULT 0,
            CONSTRAINT PK_WAHMA PRIMARY KEY (WAREKY)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE  WAHMA           IS '물류센터(창고) 마스터';
COMMENT ON COLUMN WAHMA.WAREKY   IS '창고코드 (PK)';
COMMENT ON COLUMN WAHMA.COMPKY   IS '회사코드';
COMMENT ON COLUMN WAHMA.TSPKEY   IS '운송회사';
COMMENT ON COLUMN WAHMA.DELMAK   IS '삭제플래그';
COMMENT ON COLUMN WAHMA.CHKSHA   IS '체크섀도';
COMMENT ON COLUMN WAHMA.NAME01   IS '창고명1';
COMMENT ON COLUMN WAHMA.NAME02   IS '창고명2';
COMMENT ON COLUMN WAHMA.NAME03   IS '창고명3';
COMMENT ON COLUMN WAHMA.ADDR01   IS '주소1';
COMMENT ON COLUMN WAHMA.ADDR02   IS '주소2';
COMMENT ON COLUMN WAHMA.ADDR03   IS '주소3';
COMMENT ON COLUMN WAHMA.ADDR04   IS '주소4';
COMMENT ON COLUMN WAHMA.ADDR05   IS '주소5';
COMMENT ON COLUMN WAHMA.CITY01   IS '도시';
COMMENT ON COLUMN WAHMA.REGN01   IS '지역';
COMMENT ON COLUMN WAHMA.POSTCD   IS '우편번호';
COMMENT ON COLUMN WAHMA.NATNKY   IS '국가코드';
COMMENT ON COLUMN WAHMA.TELN01   IS '전화1';
COMMENT ON COLUMN WAHMA.TELN02   IS '전화2';
COMMENT ON COLUMN WAHMA.TELN03   IS '전화3';
COMMENT ON COLUMN WAHMA.CREDAT   IS '생성일자';
COMMENT ON COLUMN WAHMA.CRETIM   IS '생성시간';
COMMENT ON COLUMN WAHMA.CREUSR   IS '생성자';
COMMENT ON COLUMN WAHMA.LMODAT   IS '수정일자';
COMMENT ON COLUMN WAHMA.LMOTIM   IS '수정시간';
COMMENT ON COLUMN WAHMA.LMOUSR   IS '수정자';
COMMENT ON COLUMN WAHMA.INDBZL   IS '삭제플래그';
COMMENT ON COLUMN WAHMA.INDARC   IS '아카이브플래그';
COMMENT ON COLUMN WAHMA.UPDCHK   IS '변경카운터';
