-- ============================================================
--  module-dispatch: DDL (Oracle 19C 호환)
--  생성일: 2026-07-15  /  원본: 01_schema.sql (MariaDB/MySQL)
--  변환규칙:
--    CREATE TABLE IF NOT EXISTS → DECLARE/EXECUTE IMMEDIATE (ORA-955 무시)
--    VARCHAR(n)                 → VARCHAR2(n CHAR)
--    INT                        → NUMBER(10)
--    DECIMAL(m,n)               → NUMBER(m,n)
--    DEFAULT ''                 → DEFAULT ' '
--    INDEX idx (col)            → 테이블 외부 CREATE INDEX (ORA-1408 무시)
--    ENGINE=InnoDB ...          → 제거
--    COMMENT '...' (인라인)   → COMMENT ON COLUMN 별도 문장
-- ============================================================

-- ── PS 배차 헤더 (PS_DISPATCH_H) ─────────────────────────
DECLARE
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE PS_DISPATCH_H (
            DISPATCH_NO  VARCHAR2(20  CHAR) NOT NULL,
            DISPATCH_DT  VARCHAR2(8   CHAR) DEFAULT '' '',
            RQSHPD       VARCHAR2(8   CHAR) DEFAULT '' '',
            DPTNKY       VARCHAR2(20  CHAR) DEFAULT '' '',
            DPTNM        VARCHAR2(100 CHAR) DEFAULT '' '',
            CARTYPE      VARCHAR2(50  CHAR) DEFAULT '' '',
            STATUS       VARCHAR2(10  CHAR) NOT NULL DEFAULT ''DRAFT'',
            TOTAL_KG     NUMBER(12,2)       DEFAULT 0,
            TOTAL_CNT    NUMBER(10)         DEFAULT 0,
            NOTE         VARCHAR2(200 CHAR) DEFAULT '' '',
            STKNUM       VARCHAR2(20  CHAR) DEFAULT NULL,
            CREDAT       VARCHAR2(8   CHAR) DEFAULT '' '',
            CREUSR       VARCHAR2(20  CHAR) DEFAULT ''SYSTEM'',
            UPDDAT       VARCHAR2(8   CHAR) DEFAULT NULL,
            CONSTRAINT PK_PS_DISPATCH_H PRIMARY KEY (DISPATCH_NO)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

DECLARE
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_PS_DISPATCH_H_RQSHPD ON PS_DISPATCH_H (RQSHPD)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1408 THEN RAISE; END IF;
END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_PS_DISPATCH_H_DPTNKY ON PS_DISPATCH_H (DPTNKY)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1408 THEN RAISE; END IF;
END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_PS_DISPATCH_H_STATUS ON PS_DISPATCH_H (STATUS)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1408 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE  PS_DISPATCH_H           IS 'PS 배차 헤더';
COMMENT ON COLUMN PS_DISPATCH_H.DISPATCH_NO IS '배차번호 (PK)';
COMMENT ON COLUMN PS_DISPATCH_H.DISPATCH_DT IS '배차일자(yyyyMMdd)';
COMMENT ON COLUMN PS_DISPATCH_H.RQSHPD     IS '납품요청일(yyyyMMdd)';
COMMENT ON COLUMN PS_DISPATCH_H.DPTNKY     IS '납품처코드';
COMMENT ON COLUMN PS_DISPATCH_H.DPTNM      IS '납품처명';
COMMENT ON COLUMN PS_DISPATCH_H.CARTYPE    IS '차종명';
COMMENT ON COLUMN PS_DISPATCH_H.STATUS     IS '상태(DRAFT/CONFIRMED/CANCELLED)';
COMMENT ON COLUMN PS_DISPATCH_H.TOTAL_KG   IS '총중량(KG)';
COMMENT ON COLUMN PS_DISPATCH_H.TOTAL_CNT  IS '총건수';
COMMENT ON COLUMN PS_DISPATCH_H.NOTE       IS '비고';
COMMENT ON COLUMN PS_DISPATCH_H.STKNUM     IS 'SAP 선적번호';
COMMENT ON COLUMN PS_DISPATCH_H.CREDAT     IS '생성일자';
COMMENT ON COLUMN PS_DISPATCH_H.CREUSR     IS '생성자';
COMMENT ON COLUMN PS_DISPATCH_H.UPDDAT     IS '수정일자';


-- ── PS 배차 아이템 (PS_DISPATCH_D) ────────────────────────
DECLARE
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE PS_DISPATCH_D (
            DISPATCH_NO  VARCHAR2(20  CHAR) NOT NULL,
            SEQ          NUMBER(10)         NOT NULL,
            SHPOKY       VARCHAR2(20  CHAR) DEFAULT '' '',
            SHPOIT       VARCHAR2(6   CHAR) DEFAULT '' '',
            SKUKEY       VARCHAR2(30  CHAR) DEFAULT '' '',
            DESC01       VARCHAR2(200 CHAR) DEFAULT '' '',
            QTSHPO       NUMBER(12,4)       DEFAULT 0,
            UOMKEY       VARCHAR2(10  CHAR) DEFAULT ''KG'',
            DPTNKY       VARCHAR2(20  CHAR) DEFAULT '' '',
            DPTNM        VARCHAR2(100 CHAR) DEFAULT '' '',
            IS_SPLIT     NUMBER(10)         NOT NULL DEFAULT 0,
            ORG_SHPOKY   VARCHAR2(20  CHAR) DEFAULT '' '',
            ORG_SHPOIT   VARCHAR2(6   CHAR) DEFAULT '' '',
            GRSWGT       NUMBER(12,4)       DEFAULT 0,
            KG_WEIGHT    NUMBER(12,4)       DEFAULT 0,
            CONSTRAINT PK_PS_DISPATCH_D PRIMARY KEY (DISPATCH_NO, SEQ),
            CONSTRAINT FK_PS_DISPATCH_D_H FOREIGN KEY (DISPATCH_NO)
                REFERENCES PS_DISPATCH_H(DISPATCH_NO) ON DELETE CASCADE
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

DECLARE
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_PS_DISPATCH_D_SHPOKY ON PS_DISPATCH_D (SHPOKY)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1408 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE  PS_DISPATCH_D             IS 'PS 배차 아이템';
COMMENT ON COLUMN PS_DISPATCH_D.DISPATCH_NO IS '배차번호 (FK)';
COMMENT ON COLUMN PS_DISPATCH_D.SEQ         IS '순번';
COMMENT ON COLUMN PS_DISPATCH_D.SHPOKY      IS '납품문서번호';
COMMENT ON COLUMN PS_DISPATCH_D.SHPOIT      IS '납품문서라인';
COMMENT ON COLUMN PS_DISPATCH_D.SKUKEY      IS '품목코드';
COMMENT ON COLUMN PS_DISPATCH_D.DESC01      IS '품목명';
COMMENT ON COLUMN PS_DISPATCH_D.QTSHPO      IS '출하수량';
COMMENT ON COLUMN PS_DISPATCH_D.UOMKEY      IS '단위';
COMMENT ON COLUMN PS_DISPATCH_D.DPTNKY      IS '납품처코드';
COMMENT ON COLUMN PS_DISPATCH_D.DPTNM       IS '납품처명';
COMMENT ON COLUMN PS_DISPATCH_D.IS_SPLIT    IS '분할여부(0/1)';
COMMENT ON COLUMN PS_DISPATCH_D.ORG_SHPOKY  IS '원본 납품문서번호';
COMMENT ON COLUMN PS_DISPATCH_D.ORG_SHPOIT  IS '원본 납품문서라인';
COMMENT ON COLUMN PS_DISPATCH_D.GRSWGT      IS '묶음당 중량(kg)';
COMMENT ON COLUMN PS_DISPATCH_D.KG_WEIGHT   IS 'KG 환산중량';


-- ── PS 배차 분할 이력 (PS_DISPATCH_SPLIT) ─────────────────
DECLARE
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE PS_DISPATCH_SPLIT (
            SPLIT_KEY   VARCHAR2(50  CHAR) NOT NULL,
            ORG_SHPOKY  VARCHAR2(20  CHAR) DEFAULT '' '',
            ORG_SHPOIT  VARCHAR2(6   CHAR) DEFAULT '' '',
            NEW_SHPOKY  VARCHAR2(20  CHAR) DEFAULT '' '',
            NEW_SHPOIT  VARCHAR2(6   CHAR) DEFAULT '' '',
            SKUKEY      VARCHAR2(30  CHAR) DEFAULT '' '',
            DESC01      VARCHAR2(200 CHAR) DEFAULT '' '',
            ORG_QTY     NUMBER(12,4)       DEFAULT 0,
            SPLIT_QTY   NUMBER(12,4)       DEFAULT 0,
            REM_QTY     NUMBER(12,4)       DEFAULT 0,
            UOMKEY      VARCHAR2(10  CHAR) DEFAULT ''KG'',
            STATUS      VARCHAR2(10  CHAR) DEFAULT ''ACTIVE'',
            CREDAT      VARCHAR2(8   CHAR) DEFAULT '' '',
            CREUSR      VARCHAR2(20  CHAR) DEFAULT ''SYSTEM'',
            CONSTRAINT PK_PS_DISPATCH_SPLIT PRIMARY KEY (SPLIT_KEY)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE  PS_DISPATCH_SPLIT            IS 'PS 배차 분할 이력';
COMMENT ON COLUMN PS_DISPATCH_SPLIT.SPLIT_KEY  IS '분할키 (PK)';
COMMENT ON COLUMN PS_DISPATCH_SPLIT.ORG_SHPOKY IS '원본 납품문서번호';
COMMENT ON COLUMN PS_DISPATCH_SPLIT.ORG_SHPOIT IS '원본 납품문서라인';
COMMENT ON COLUMN PS_DISPATCH_SPLIT.NEW_SHPOKY IS '신규 납품문서번호';
COMMENT ON COLUMN PS_DISPATCH_SPLIT.NEW_SHPOIT IS '신규 납품문서라인';
COMMENT ON COLUMN PS_DISPATCH_SPLIT.SKUKEY     IS '품목코드';
COMMENT ON COLUMN PS_DISPATCH_SPLIT.DESC01     IS '품목명';
COMMENT ON COLUMN PS_DISPATCH_SPLIT.ORG_QTY    IS '원본 수량';
COMMENT ON COLUMN PS_DISPATCH_SPLIT.SPLIT_QTY  IS '분할 수량';
COMMENT ON COLUMN PS_DISPATCH_SPLIT.REM_QTY    IS '잔여 수량';
COMMENT ON COLUMN PS_DISPATCH_SPLIT.UOMKEY     IS '단위';
COMMENT ON COLUMN PS_DISPATCH_SPLIT.STATUS     IS '상태';
COMMENT ON COLUMN PS_DISPATCH_SPLIT.CREDAT     IS '생성일자';
COMMENT ON COLUMN PS_DISPATCH_SPLIT.CREUSR     IS '생성자';


-- ── SAP 선적 연동 (PS_SAP_STK) ────────────────────────────
DECLARE
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE PS_SAP_STK (
            STDLNR       VARCHAR2(20  CHAR) NOT NULL,
            SAP_STKNUM   VARCHAR2(20  CHAR) DEFAULT '' '',
            DISPATCH_NO  VARCHAR2(20  CHAR) DEFAULT '' '',
            RQSHPD_FROM  VARCHAR2(8   CHAR) DEFAULT '' '',
            RQSHPD_TO    VARCHAR2(8   CHAR) DEFAULT '' '',
            DPTNKY       VARCHAR2(20  CHAR) DEFAULT '' '',
            DPTNKYNM     VARCHAR2(100 CHAR) DEFAULT '' '',
            CARTYPE      VARCHAR2(50  CHAR) DEFAULT '' '',
            CARCLASS_CD  VARCHAR2(20  CHAR) DEFAULT '' '',
            VEHINO       VARCHAR2(20  CHAR) DEFAULT '' '',
            CARNO        VARCHAR2(20  CHAR) DEFAULT '' '',
            DRIVER       VARCHAR2(50  CHAR) DEFAULT '' '',
            DRIVERCEL    VARCHAR2(20  CHAR) DEFAULT '' '',
            TOTAL_KG     NUMBER(12,2)       DEFAULT 0,
            SVBELN_CNT   NUMBER(10)         DEFAULT 0,
            STATUS       VARCHAR2(10  CHAR) DEFAULT ''DRAFT'',
            CREDAT       VARCHAR2(8   CHAR) DEFAULT '' '',
            CREUSR       VARCHAR2(20  CHAR) DEFAULT ''SYSTEM'',
            CONSTRAINT PK_PS_SAP_STK PRIMARY KEY (STDLNR)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE  PS_SAP_STK              IS 'SAP 선적 연동';
COMMENT ON COLUMN PS_SAP_STK.STDLNR      IS 'SAP 배송번호 (PK)';
COMMENT ON COLUMN PS_SAP_STK.SAP_STKNUM  IS 'SAP 선적번호';
COMMENT ON COLUMN PS_SAP_STK.DISPATCH_NO IS '배차번호 (FK)';
COMMENT ON COLUMN PS_SAP_STK.RQSHPD_FROM IS '납품요청일 FROM';
COMMENT ON COLUMN PS_SAP_STK.RQSHPD_TO  IS '납품요청일 TO';
COMMENT ON COLUMN PS_SAP_STK.DPTNKY     IS '납품처코드';
COMMENT ON COLUMN PS_SAP_STK.DPTNKYNM   IS '납품처명';
COMMENT ON COLUMN PS_SAP_STK.CARTYPE    IS '차종';
COMMENT ON COLUMN PS_SAP_STK.CARCLASS_CD IS '차량클래스';
COMMENT ON COLUMN PS_SAP_STK.VEHINO     IS '차량번호';
COMMENT ON COLUMN PS_SAP_STK.CARNO      IS '차호';
COMMENT ON COLUMN PS_SAP_STK.DRIVER     IS '기사명';
COMMENT ON COLUMN PS_SAP_STK.DRIVERCEL  IS '기사연락처';
COMMENT ON COLUMN PS_SAP_STK.TOTAL_KG   IS '총중량';
COMMENT ON COLUMN PS_SAP_STK.SVBELN_CNT IS '배송문서 건수';
COMMENT ON COLUMN PS_SAP_STK.STATUS     IS '상태';
COMMENT ON COLUMN PS_SAP_STK.CREDAT     IS '생성일자';
COMMENT ON COLUMN PS_SAP_STK.CREUSR     IS '생성자';


-- ── 운송비 마스터 (ROUTE_COST) ────────────────────────────
DECLARE
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ROUTE_COST (
            SHPPT       VARCHAR2(10  CHAR) NOT NULL DEFAULT '' '',
            ROUTE       VARCHAR2(20  CHAR) NOT NULL DEFAULT '' '',
            PTNRKY      VARCHAR2(10  CHAR) NOT NULL DEFAULT '' '',
            CARCLASS    VARCHAR2(20  CHAR) NOT NULL DEFAULT '' '',
            COST        NUMBER(12,2),
            UNIT        VARCHAR2(10  CHAR) DEFAULT ''KRW'',
            DATE_START  VARCHAR2(8   CHAR) DEFAULT '' '',
            DATE_END    VARCHAR2(8   CHAR) DEFAULT '' '',
            CREDAT      VARCHAR2(8   CHAR) DEFAULT '' '',
            CRETIM      VARCHAR2(6   CHAR) DEFAULT '' '',
            CREUSR      VARCHAR2(20  CHAR) DEFAULT ''ADMIN'',
            LMODAT      VARCHAR2(8   CHAR) DEFAULT '' '',
            LMOTIM      VARCHAR2(6   CHAR) DEFAULT '' '',
            LMOUSR      VARCHAR2(20  CHAR) DEFAULT ''ADMIN'',
            CONSTRAINT PK_ROUTE_COST PRIMARY KEY (ROUTE, PTNRKY, CARCLASS)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

DECLARE
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_ROUTE_COST_SHPPT  ON ROUTE_COST (SHPPT)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1408 THEN RAISE; END IF;
END;
/
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_ROUTE_COST_PTNRKY ON ROUTE_COST (PTNRKY)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1408 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE  ROUTE_COST           IS '운송비 마스터';
COMMENT ON COLUMN ROUTE_COST.SHPPT     IS '출하지점';
COMMENT ON COLUMN ROUTE_COST.ROUTE     IS '경로코드';
COMMENT ON COLUMN ROUTE_COST.PTNRKY   IS '납품처코드';
COMMENT ON COLUMN ROUTE_COST.CARCLASS  IS '차량클래스';
COMMENT ON COLUMN ROUTE_COST.COST      IS '운송비(원)';
COMMENT ON COLUMN ROUTE_COST.UNIT      IS '통화단위';
COMMENT ON COLUMN ROUTE_COST.DATE_START IS '적용시작일';
COMMENT ON COLUMN ROUTE_COST.DATE_END  IS '적용종료일';
COMMENT ON COLUMN ROUTE_COST.CREDAT    IS '생성일자';
COMMENT ON COLUMN ROUTE_COST.CRETIM    IS '생성시간';
COMMENT ON COLUMN ROUTE_COST.CREUSR    IS '생성자';
COMMENT ON COLUMN ROUTE_COST.LMODAT    IS '수정일자';
COMMENT ON COLUMN ROUTE_COST.LMOTIM    IS '수정시간';
COMMENT ON COLUMN ROUTE_COST.LMOUSR    IS '수정자';
