-- =====================================================================
--  BATCH: 납품처관리 — 최대톤수(MAX_TON) 일괄 등록
-- ---------------------------------------------------------------------
--  대상 DB   : Oracle 19C  (스키마 KNRAWMS)
--  대상 테이블: KNRAWMS.BZPTN_DETAIL
--  키 조건   : PTNRKY=<납품처코드> AND PTNRTY='CT' AND OWNRKY='KN'
--
--  배경:
--    납품처관리 화면에서 납품처별 최대톤수(MAX_TON)를 하나씩 등록하는 대신,
--    운영 담당자가 제공한 엑셀(ps최대진입톤수.xlsx)의
--    '납품처코드 / 진입가능 차량' 표를 기준으로 일괄 등록한다.
--
--  매핑 규칙:
--    진입가능 차량 텍스트의 톤수를 MAX_TON(ton) 숫자값으로 그대로 사용.
--      '1.4톤' -> 1.4 / '3.5톤' -> 3.5 / '5톤' -> 5 / '8톤' -> 8
--
--  중복 코드 처리(작은 값 기준):
--    같은 납품처코드가 서로 다른 톤수로 중복 등장한 경우, 통과 가능한
--    가장 작은 차량 기준으로 안전하게 '작은 값(min)'을 채택한다.
--      405630 : 1.4 / 3.5  -> 1.4
--      401237 : 1.4 / 3.5  -> 1.4
--      400269 : 3.5 / 5.0  -> 3.5
--    (그 외 중복 6건은 값이 동일하여 결과 동일)
--
--  대상 코드 수: 76개 (엑셀 원본 85행 -> 고유 76코드)
--    - 1.4톤 :  6개
--    - 3.5톤 : 31개
--    - 5.0톤 : 38개
--    - 8.0톤 :  1개
--
--  선행 조건:
--    본 스크립트 실행 전 MAX_TON 컬럼이 존재해야 한다.
--    미존재 시 sql/FIX_BZPTN_DETAIL_ADD_MAX_TON.sql 을 먼저 실행할 것.
--
--  주의:
--    - 존재하지 않는 (PTNRKY,PTNRTY,OWNRKY) 조합은 UPDATE 0건으로 무시된다
--      (신규 INSERT 하지 않음 — 납품처관리에 이미 등록된 납품처만 대상).
--    - 아래 익명 PL/SQL 블록은 실행 후 자동 COMMIT 하지 않는다.
--      결과 확인(맨 아래 SELECT) 후 정상이면 수동으로 COMMIT; 하거나,
--      익명블록 끝의 COMMIT; 주석을 해제하여 사용한다.
-- =====================================================================

-- (선행) MAX_TON 컬럼 존재 확인 — 0건이면 FIX_BZPTN_DETAIL_ADD_MAX_TON.sql 먼저 실행
SELECT COUNT(*) AS MAX_TON_COL_EXISTS
  FROM ALL_TAB_COLUMNS
 WHERE OWNER='KNRAWMS' AND TABLE_NAME='BZPTN_DETAIL' AND COLUMN_NAME='MAX_TON';

-- ---------------------------------------------------------------------
--  일괄 UPDATE (76건)
-- ---------------------------------------------------------------------
DECLARE
    v_dt VARCHAR2(8)  := TO_CHAR(SYSDATE,'YYYYMMDD');
    v_tm VARCHAR2(6)  := TO_CHAR(SYSDATE,'HH24MISS');
    v_upd NUMBER := 0;
BEGIN
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='100579' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='100596' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='101116' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='101131' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='101188' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400014' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400225' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400250' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400254' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400264' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400269' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=1.4, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400290' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400297' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400316' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400343' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400345' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400466' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400650' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400687' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400704' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400877' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400886' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400911' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='400922' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='401008' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='401025' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='401102' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='401131' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='401167' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=1.4, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='401237' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='401456' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='401627' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='403018' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='403247' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='403475' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='403498' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='403517' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=8, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='405167' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='405359' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='405533' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='405598' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=1.4, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='405630' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='405658' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='405683' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='406247' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='406918' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='407253' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='407423' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='407508' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='407737' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=1.4, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='407786' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='407827' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='407875' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='407914' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='407972' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='407984' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='408175' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='408343' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='408434' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='408642' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='408913' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='408978' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='409866' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='409938' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=1.4, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='420070' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='420279' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='420315' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='470023' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='470067' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='470078' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='470166' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='470182' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=1.4, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='470191' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='470215' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='480017' AND PTNRTY='CT' AND OWNRKY='KN';
    UPDATE KNRAWMS.BZPTN_DETAIL SET MAX_TON=3.5, LMODAT=v_dt, LMOTIM=v_tm, LMOUSR='BATCH' WHERE PTNRKY='480106' AND PTNRTY='CT' AND OWNRKY='KN';
    v_upd := SQL%ROWCOUNT;  -- 마지막 UPDATE 반영건 (참고용)
    DBMS_OUTPUT.PUT_LINE('MAX_TON batch executed. (last stmt rows=' || v_upd || ')');
    -- 결과 확인 후 정상이면 아래 COMMIT 주석 해제 또는 수동 COMMIT;
    -- COMMIT;
END;
/

-- ---------------------------------------------------------------------
--  검증: 방금 등록된 값 확인 (톤별 건수)
-- ---------------------------------------------------------------------
SELECT MAX_TON, COUNT(*) AS CNT
  FROM KNRAWMS.BZPTN_DETAIL
 WHERE PTNRTY='CT' AND OWNRKY='KN'
   AND PTNRKY IN (
     '400290','401237','405630','407786','420070','470191',
     '100579','100596','101131','400269','400297','400345','400704','400886','400911','401167','403018','403247','403475','405359','405598','405658','406247','406918','407508','407875','407972','407984','408642','408913','408978','409866','409938','420315','470182','480017','480106',
     '101116','101188','400014','400225','400250','400254','400264','400316','400343','400466','400650','400687','400877','400922','401008','401025','401102','401131','401456','401627','403498','403517','405533','405683','407253','407423','407737','407827','407914','408175','408343','408434','420279','470023','470067','470078','470166','470215',
     '405167'
   )
 GROUP BY MAX_TON
 ORDER BY MAX_TON;

-- 상세 확인
SELECT PTNRKY, MAX_TON, LMODAT, LMOTIM, LMOUSR
  FROM KNRAWMS.BZPTN_DETAIL
 WHERE PTNRTY='CT' AND OWNRKY='KN' AND LMOUSR='BATCH'
 ORDER BY PTNRKY;
