-- =====================================================================
--  FIX: 납품처 상세조회 ORA-00904 "BD1_0"."DETAIL_ID"
--       — BZPTN_DETAIL 에 PK(DETAIL_ID IDENTITY) 추가
-- ---------------------------------------------------------------------
--  대상 DB   : Oracle 19C  (스키마 KNRAWMS)
--  대상 테이블: KNRAWMS.BZPTN_DETAIL
--
--  배경:
--    상세조회는 JPA 엔티티(BzptnDetail)로 조회하며, 엔티티는
--      @Id @GeneratedValue(strategy = IDENTITY)
--      @Column(name = "DETAIL_ID") Long detailId;
--    로 DETAIL_ID 를 PK 로 매핑한다. 운영 Oracle 테이블에 DETAIL_ID 컬럼이
--    없으면 상세조회 SELECT 가 ORA-00904 로 실패한다.
--    → DETAIL_ID 를 Oracle 12c+ IDENTITY 컬럼(PK)으로 추가한다.
--
--  주의:
--    - GENERATED BY DEFAULT ON NULL AS IDENTITY : 기존 행에도 순번이 채워지고,
--      INSERT 시 값 미지정이면 자동 채번(엔티티 IDENTITY 전략과 호환).
--    - 이미 다른 PK 가 있으면 PK 추가는 건너뛴다(중복 PK 방지).
--    - 반복 실행해도 안전(컬럼/PK 존재 여부 확인 후 실행).
-- =====================================================================

DECLARE
    v_col NUMBER;
    v_pk  NUMBER;
BEGIN
    -- 1) DETAIL_ID 컬럼 존재 확인 → 없으면 IDENTITY 컬럼으로 추가
    SELECT COUNT(*) INTO v_col
      FROM ALL_TAB_COLUMNS
     WHERE OWNER='KNRAWMS' AND TABLE_NAME='BZPTN_DETAIL' AND COLUMN_NAME='DETAIL_ID';

    IF v_col = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE KNRAWMS.BZPTN_DETAIL ADD ' ||
            '(DETAIL_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY)';
        DBMS_OUTPUT.PUT_LINE('ADDED  : DETAIL_ID (IDENTITY)');
    ELSE
        DBMS_OUTPUT.PUT_LINE('EXISTS : DETAIL_ID');
    END IF;

    -- 2) 기존 PK 없을 때만 DETAIL_ID 를 PK 로 지정
    SELECT COUNT(*) INTO v_pk
      FROM ALL_CONSTRAINTS
     WHERE OWNER='KNRAWMS' AND TABLE_NAME='BZPTN_DETAIL' AND CONSTRAINT_TYPE='P';

    IF v_pk = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE KNRAWMS.BZPTN_DETAIL ' ||
            'ADD CONSTRAINT PK_BZPTN_DETAIL PRIMARY KEY (DETAIL_ID)';
        DBMS_OUTPUT.PUT_LINE('ADDED  : PK_BZPTN_DETAIL (DETAIL_ID)');
    ELSE
        DBMS_OUTPUT.PUT_LINE('SKIP   : PK already exists');
    END IF;
END;
/

-- 확인 (A) DETAIL_ID 컬럼/IDENTITY 여부
SELECT COLUMN_NAME, DATA_TYPE, IDENTITY_COLUMN, NULLABLE
  FROM ALL_TAB_COLUMNS
 WHERE OWNER='KNRAWMS' AND TABLE_NAME='BZPTN_DETAIL' AND COLUMN_NAME='DETAIL_ID';

-- 확인 (B) PK 제약
SELECT ac.CONSTRAINT_NAME, ac.CONSTRAINT_TYPE, acc.COLUMN_NAME
  FROM ALL_CONSTRAINTS ac
  JOIN ALL_CONS_COLUMNS acc
    ON ac.OWNER=acc.OWNER AND ac.CONSTRAINT_NAME=acc.CONSTRAINT_NAME
 WHERE ac.OWNER='KNRAWMS' AND ac.TABLE_NAME='BZPTN_DETAIL'
   AND ac.CONSTRAINT_TYPE='P';
