-- =============================================================
--  DS_DISPATCH_CONST_ITEM 기본 데이터 삽입
--  ITEM_CD = DS_DISPATCH_CONST.CONST_KEY 기준 (총 58건)
--  그룹: COMMON(5), ROLL(17), BOARD(14), MIX(6),
--        GLOBAL(6), CARGO(3), COST(2), DYNAMIC_ZONE(4), VEHICLE(1)
--  생성일: 2026-07-15
-- =============================================================

INSERT INTO DS_DISPATCH_CONST_ITEM
    (ITEM_CD, ITEM_NM, ITEM_GRP, ITEM_TYPE, DEFAULT_VAL, UNIT, CONST_OP,
     SORT_SEQ, DESCRIPTION, SOURCE_REF, ACTIVE_YN, SELECT_OPTS, CREDAT, LMODAT)
VALUES
    -- ─── 공통 제약 (COMMON) §1 ─────────────────────────────
    ('ENTRY_TON_LIMIT', '납품처 진입 허용 톤수 제한', 'COMMON', 'NUM', '0', 'ton', '<=',
     10, '납품처 마스터에 설정된 최대 진입 허용 톤수 초과 차량은 배차 후보에서 제외', '§1-1', 'Y', NULL, CURDATE(), CURDATE()),
    ('PALLET_YN', '납품처 파레트 유무 조건', 'COMMON', 'YN', 'Y', 'Y/N', '=',
     20, '납품처 마스터의 파레트 필수 여부 → 파레트 높이 반영 여부 결정', '§1-2', 'Y', NULL, CURDATE(), CURDATE()),
    ('FIXED_VEH_PRIORITY', '고정차량 배차 최우선 반영', 'COMMON', 'YN', 'Y', 'Y/N', '=',
     30, '고정 차량 매핑 오더는 알고리즘 연산 전 최우선 사전 할당(Pre-assignment)', '§1-3', 'Y', NULL, CURDATE(), CURDATE()),
    ('DYNAMIC_ALLOW_YN', '동적 라우팅 허용 여부', 'COMMON', 'YN', 'Y', 'Y/N', '=',
     40, '납품처 마스터의 동적 라우팅 허용 여부 → 고정 노선 vs 유연 배차 분리', '§1-4', 'Y', NULL, CURDATE(), CURDATE()),
    ('SPLIT_DELIVERY_YN', '납품수량 초과 시 분할 선적', 'COMMON', 'YN', 'Y', 'Y/N', '=',
     50, '주문 수량이 최대 차량 적재 능력 초과 시 잔여 수량 오더 분할', '§1-5', 'Y', NULL, CURDATE(), CURDATE()),
    -- ─── 원지 제약 (ROLL) §2 ───────────────────────────────
    ('ROLL_INTEGER_ONLY', '원지 정수 롤 단위 강제 (분할 절대 불가)', 'ROLL', 'YN', 'Y', '', '=',
     110, '원지 정수 롤 단위 강제 (분할 절대 불가)', '§2-1', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_SPLIT_ALLOWED', '원지 분할 배차 금지 (엑셀§2-1)', 'ROLL', 'YN', 'N', '', '=',
     120, '원지 분할 배차 금지 (엑셀§2-1)', '§2-1', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_MAX_TIER', '롤 최대 적재 단수 Hard Cap (3단)', 'ROLL', 'NUM', '3', 'm', '<=',
     130, '롤 최대 적재 단수 Hard Cap (3단)', '§2-2', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_MIN_QTY', '원지 최소 배차 수량 (1롤)', 'ROLL', 'NUM', '1', 'm', '>=',
     130, '원지 최소 배차 수량 (1롤)', '§2-1', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_PALLET_DEDUCT_M', '파레트 높이 차감값 (m) — 0.15m 기본', 'ROLL', 'NUM', '0.15', 'm', '=',
     140, '파레트 높이 차감값 (m) — 0.15m 기본', '§2-2', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_INCH_MIX_ALLOW', '인치/평량 혼합 오더 허용 (엑셀§2-3)', 'ROLL', 'YN', 'Y', 'm', '=',
     150, '인치/평량 혼합 오더 허용 (엑셀§2-3)', '§2-3', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_PALLET_APPLY_YN', '파레트 차감 적용 여부 (납품처 FORKLIFT_YN=N 시 적용)', 'ROLL', 'YN', 'Y', '', '=',
     150, '파레트 차감 적용 여부 (납품처 FORKLIFT_YN=N 시 적용)', '§2-2', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_2D_PACK_ENGINE', '혼합 규격 시 2D 바닥 패킹 연산 적용', 'ROLL', 'YN', 'Y', '', '=',
     160, '혼합 규격 시 2D 바닥 패킹 연산 적용', '§2-3', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_HEIGHT_MARGIN_M', '적재 높이 안전 여유 마진 (m)', 'ROLL', 'NUM', '0', 'm', '=',
     160, '적재 높이 안전 여유 마진 (m)', '§2-2', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_3D_CHECK_YN', '원지 3D 블록 검증 활성 (Dead Space 포함)', 'ROLL', 'YN', 'Y', '', '=',
     170, '원지 3D 블록 검증 활성 (Dead Space 포함)', '§2-4', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_SAME_INCH_FORCE', '동일 인치 강제 여부 (N=혼재허용)', 'ROLL', 'YN', 'N', '', '=',
     170, '동일 인치 강제 여부 (N=혼재허용)', '§2-3', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_3D_DEAD_SPACE_PCT', 'Dead Space 허용 비율 (%) — 0=허용안함', 'ROLL', 'NUM', '0', '%', '<=',
     180, 'Dead Space 허용 비율 (%) — 0=허용안함', '§2-4', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_REF_12INCH_LT300', '12인치/평량300미만 차종별 1단 기준수(1.4t~18t)', 'ROLL', 'CSV', '2,3,4,6,8,8,8', '롤', '=',
     180, '12인치/평량300미만 차종별 1단 기준수(1.4t~18t)', '§2-3', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_OVERSIZE_ACTION', '치수 초과 시 처리 방식 (SPLIT=분할/REJECT=제외)', 'ROLL', 'SELECT', 'SPLIT', '', '=',
     190, '치수 초과 시 처리 방식 (SPLIT=분할/REJECT=제외)', '§2-4', 'Y', '["SPLIT","REJECT"]', CURDATE(), CURDATE()),
    ('ROLL_REF_12INCH_GE300', '12인치/평량300이상 차종별 1단 기준수(1.4t~18t)', 'ROLL', 'CSV', '2,3,4,5,7,7,7', '롤', '=',
     190, '12인치/평량300이상 차종별 1단 기준수(1.4t~18t)', '§2-3', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_REF_3INCH_LT300', '3인치/평량300미만 차종별 1단 기준수(1.4t~18t)', 'ROLL', 'CSV', '3,5,10,12,14,14,15', '롤', '=',
     200, '3인치/평량300미만 차종별 1단 기준수(1.4t~18t)', '§2-3', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_REF_3INCH_GE300', '3인치/평량300이상 차종별 1단 기준수(1.4t~18t)', 'ROLL', 'CSV', '3,5,10,12,14,14,15', '롤', '=',
     210, '3인치/평량300이상 차종별 1단 기준수(1.4t~18t)', '§2-3', 'Y', NULL, CURDATE(), CURDATE()),
    -- ─── 판지 제약 (BOARD) §3 ──────────────────────────────
    ('BOARD_CBM_CHECK_YN', '판지 CBM 자동계산 + Double-Threshold 검증 활성 (엑셀§3-1)', 'BOARD', 'YN', 'Y', '', '=',
     310, '판지 CBM 자동계산 + Double-Threshold 검증 활성 (엑셀§3-1)', '§3-1', 'Y', NULL, CURDATE(), CURDATE()),
    ('BOARD_MAX_CBM_RATIO', '가용 적재함 CBM 상한 (%)', 'BOARD', 'NUM', '100', 'm', '<=',
     320, '가용 적재함 CBM 상한 (%)', '§3-1', 'Y', NULL, CURDATE(), CURDATE()),
    ('BOARD_BULK_INTEGER_ONLY', '벌크 1PLT 단위 강제 (개체 내 분할 불가)', 'BOARD', 'YN', 'Y', '', '=',
     330, '벌크 1PLT 단위 강제 (개체 내 분할 불가)', '§3-2', 'Y', NULL, CURDATE(), CURDATE()),
    ('BOARD_MAX_TON_RATIO', '중량 상한 (%) — Double-Threshold 중량 기준', 'BOARD', 'NUM', '100', 'm', '<=',
     330, '중량 상한 (%) — Double-Threshold 중량 기준', '§3-1', 'Y', NULL, CURDATE(), CURDATE()),
    ('BOARD_INNER_SPLIT_ALLOW', '속포장 속 단위 분할 허용', 'BOARD', 'YN', 'Y', '', '=',
     340, '속포장 속 단위 분할 허용', '§3-2', 'Y', NULL, CURDATE(), CURDATE()),
    ('BOARD_DUAL_THRESHOLD', '중량+CBM 동시 초과 이중 임계치 검증 활성', 'BOARD', 'YN', 'Y', '', '=',
     340, '중량+CBM 동시 초과 이중 임계치 검증 활성', '§3-1', 'Y', NULL, CURDATE(), CURDATE()),
    ('BOARD_INNER_STACK_ALLOW', '분할된 속을 판지 위 추가 적재 허용', 'BOARD', 'YN', 'Y', '', '=',
     350, '분할된 속을 판지 위 추가 적재 허용', '§3-2', 'Y', NULL, CURDATE(), CURDATE()),
    ('BOARD_FLEX_SPLIT_YN', '유연 분할 선적 활성 — 차량 한계 시 초과분만 후속 차량 (엑셀§3-3)', 'BOARD', 'YN', 'Y', '', '=',
     350, '유연 분할 선적 활성 — 차량 한계 시 초과분만 후속 차량 (엑셀§3-3)', '§3-3', 'Y', NULL, CURDATE(), CURDATE()),
    ('BOARD_INNER_OVERFLOW_ACT', '속포장 초과 시 처리 (SPLIT=다음 차량 배정)', 'BOARD', 'SELECT', 'SPLIT', '', '=',
     360, '속포장 초과 시 처리 (SPLIT=다음 차량 배정)', '§3-2', 'Y', '["SPLIT","REJECT"]', CURDATE(), CURDATE()),
    ('BOARD_SPLIT_UNIT', '분할 단위 (EA=낱개속, PLT=파레트)', 'BOARD', 'SELECT', 'EA', '', '=',
     360, '분할 단위 (EA=낱개속, PLT=파레트)', '§3-3', 'Y', '["EA","PLT"]', CURDATE(), CURDATE()),
    ('BOARD_3D_CHECK_YN', '판지 3D 블록 검증 활성 (Dead Space 포함)', 'BOARD', 'YN', 'Y', '', '=',
     370, '판지 3D 블록 검증 활성 (Dead Space 포함)', '§3-4', 'Y', NULL, CURDATE(), CURDATE()),
    ('BOARD_SPLIT_OVERFLOW', '초과분(속단위) 후속 차량 정확 배정 활성', 'BOARD', 'YN', 'Y', '', '=',
     370, '초과분(속단위) 후속 차량 정확 배정 활성', '§3-3', 'Y', NULL, CURDATE(), CURDATE()),
    ('BOARD_3D_DEAD_SPACE_PCT', '판지 Dead Space 허용 비율 (%)', 'BOARD', 'NUM', '0', '%', '<=',
     380, '판지 Dead Space 허용 비율 (%)', '§3-4', 'Y', NULL, CURDATE(), CURDATE()),
    ('BOARD_HEIGHT_MAX_M', '판지 스택 최대 높이 (m, 기본 2.4m)', 'BOARD', 'NUM', '2.4', 'm', '<=',
     390, '판지 스택 최대 높이 (m, 기본 2.4m)', '§3-4', 'Y', NULL, CURDATE(), CURDATE()),
    -- ─── 혼합적재 제약 (MIX) §4 ────────────────────────────
    ('MIX_ROLL_BOTTOM_FORCE', '원지 하단·판지 상단 강제 고정 (물리적 압착 파손 방지 핵심)', 'MIX', 'YN', 'Y', '', '=',
     510, '원지 하단·판지 상단 강제 고정 (물리적 압착 파손 방지 핵심)', '§4-1', 'Y', NULL, CURDATE(), CURDATE()),
    ('MIX_LIFO_ENABLE', '복수 납품처 LIFO 배치 활성 (나중하차→안쪽, 먼저하차→문쪽)', 'MIX', 'YN', 'Y', '', '=',
     520, '복수 납품처 LIFO 배치 활성 (나중하차→안쪽, 먼저하차→문쪽)', '§4-2', 'Y', NULL, CURDATE(), CURDATE()),
    ('MIX_ZONE_SPLIT_YN', '원지·판지 배송처 상이 시 전후 Zone 분할 적재 자동 전환', 'MIX', 'YN', 'Y', '', '=',
     530, '원지·판지 배송처 상이 시 전후 Zone 분할 적재 자동 전환', '§4-2', 'Y', NULL, CURDATE(), CURDATE()),
    ('MIX_WEIGHT_CHECK_YN', '혼적 총중량 검증 (원지+판지 ≤ 차량 최대 적재 중량)', 'MIX', 'YN', 'Y', '', '=',
     540, '혼적 총중량 검증 (원지+판지 ≤ 차량 최대 적재 중량)', '§4-3', 'Y', NULL, CURDATE(), CURDATE()),
    ('MIX_HEIGHT_CHECK_YN', '혼적 높이 검증 (파렛트고+원지다단높이+판지높이 ≤ 차량 최대 높이)', 'MIX', 'YN', 'Y', 'm', '=',
     550, '혼적 높이 검증 (파렛트고+원지다단높이+판지높이 ≤ 차량 최대 높이)', '§4-3', 'Y', NULL, CURDATE(), CURDATE()),
    ('MIX_3D_CHECK_YN', '혼적 Dead Space 포함 3D 블록 종합 검증', 'MIX', 'YN', 'Y', '', '=',
     560, '혼적 Dead Space 포함 3D 블록 종합 검증', '§4-3', 'Y', NULL, CURDATE(), CURDATE()),
    -- ─── 전역 제약 (GLOBAL) ────────────────────────────────
    ('MAX_VEHICLES_PER_GROUP', '그룹당 최대 배차 차량 수', 'GLOBAL', 'NUM', '99', '', '<=',
     1010, '그룹당 최대 배차 차량 수', '§GLOBAL', 'Y', NULL, CURDATE(), CURDATE()),
    ('ALLOW_SPLIT_ITEM', '단일 아이템 납품분할 허용', 'GLOBAL', 'YN', 'Y', '', '=',
     1020, '단일 아이템 납품분할 허용', '§GLOBAL', 'Y', NULL, CURDATE(), CURDATE()),
    ('ALLOW_MIXED_LOAD', '우편번호 앞 3자리 동일 납품처 혼적 허용', 'GLOBAL', 'YN', 'N', 'm', '=',
     1030, '우편번호 앞 3자리 동일 납품처 혼적 허용', '§GLOBAL', 'Y', NULL, CURDATE(), CURDATE()),
    ('MIN_FILL_RATIO', '최소 적재율(%) — 0=제한없음', 'GLOBAL', 'NUM', '0', '%', '>=',
     1040, '최소 적재율(%) — 0=제한없음', '§GLOBAL', 'Y', NULL, CURDATE(), CURDATE()),
    ('MAX_FILL_RATIO', '최대 적재율(%) — 초과배차 방지', 'GLOBAL', 'NUM', '100', '%', '<=',
     1050, '최대 적재율(%) — 초과배차 방지', '§GLOBAL', 'Y', NULL, CURDATE(), CURDATE()),
    ('BOARD_MIN_FILL_RATIO', '판지 전용 최소 적재율(%) — 0=미적용, 값설정 시 적재율 하한 강제 (BOARD_BULK_INTEGER_ONLY 연계)', 'GLOBAL', 'NUM', '0', 'm', '>=',
     1060, '판지 전용 최소 적재율(%) — 0=미적용, 값설정 시 적재율 하한 강제 (BOARD_BULK_INTEGER_ONLY 연계)', '§GLOBAL', 'Y', NULL, CURDATE(), CURDATE()),
    -- ─── 화물 제약 (CARGO) ─────────────────────────────────
    ('MAX_ROLL_STACK_TIER', '최대 롤 적재 단수', 'CARGO', 'NUM', '2', '단', '<=',
     1110, '최대 롤 적재 단수', '§CARGO', 'Y', NULL, CURDATE(), CURDATE()),
    ('MAX_BOARD_HEIGHT_M', '판지 최대 적재 높이(m)', 'CARGO', 'NUM', '2.4', 'm', '<=',
     1120, '판지 최대 적재 높이(m)', '§CARGO', 'Y', NULL, CURDATE(), CURDATE()),
    ('ROLL_SINGLE_KG_FALLBACK', '롤 단중 미등록 시 fallback(kg)', 'CARGO', 'NUM', '600', '', '=',
     1130, '롤 단중 미등록 시 fallback(kg)', '§CARGO', 'Y', NULL, CURDATE(), CURDATE()),
    -- ─── 비용 제약 (COST) ──────────────────────────────────
    ('COST_REF_DATE', '운송비 기준일 (TODAY or YYYYMMDD)', 'COST', 'TEXT', 'TODAY', '롤', '=',
     1210, '운송비 기준일 (TODAY or YYYYMMDD)', '§COST', 'Y', NULL, CURDATE(), CURDATE()),
    ('COST_PENALTY_OVER', '초과적재 비용 패널티 배수', 'COST', 'NUM', '1.5', '', '=',
     1220, '초과적재 비용 패널티 배수', '§COST', 'Y', NULL, CURDATE(), CURDATE()),
    -- ─── 동적배차 구역 (DYNAMIC_ZONE) ─────────────────────
    ('DYNAMIC_GROUP_BY', '동적 그룹핑 기준 컬럼 — 동일 AREA_CD(권역) 납품처끼리 동적 배차 그룹 형성', 'DYNAMIC_ZONE', 'TEXT', 'AREA_CD', '', '=',
     1310, '동적 그룹핑 기준 컬럼 — 동일 AREA_CD(권역) 납품처끼리 동적 배차 그룹 형성', '§DYN', 'Y', NULL, CURDATE(), CURDATE()),
    ('DYNAMIC_DEFAULT_YN', '납품처 DYNAMIC_YN 미설정 시 기본값 (Y=동적배차 가능, N=불가)', 'DYNAMIC_ZONE', 'YN', 'Y', '', '=',
     1320, '납품처 DYNAMIC_YN 미설정 시 기본값 (Y=동적배차 가능, N=불가)', '§DYN', 'Y', NULL, CURDATE(), CURDATE()),
    ('DYNAMIC_MIN_GROUP_SIZE', '동적 그룹 최소 납품처 수 — 1=단독 납품처도 동적배차 허용', 'DYNAMIC_ZONE', 'NUM', '1', 'm', '>=',
     1330, '동적 그룹 최소 납품처 수 — 1=단독 납품처도 동적배차 허용', '§DYN', 'Y', NULL, CURDATE(), CURDATE()),
    ('DYNAMIC_AREA_FORCE_YN', '동일 구역(AREA_CD) 내 DYNAMIC_YN=Y 납품처는 반드시 동적 그룹 편입 강제', 'DYNAMIC_ZONE', 'YN', 'Y', '', '=',
     1340, '동일 구역(AREA_CD) 내 DYNAMIC_YN=Y 납품처는 반드시 동적 그룹 편입 강제', '§DYN', 'Y', NULL, CURDATE(), CURDATE()),
    -- ─── 차량 (VEHICLE) ────────────────────────────────────
    ('ALLOW_CARTYPE', '차종 허용여부', 'VEHICLE', 'YN', 'Y', '', '=',
     9010, '차종 허용여부', '', 'Y', NULL, CURDATE(), CURDATE())
ON DUPLICATE KEY UPDATE
    ITEM_NM      = VALUES(ITEM_NM),
    ITEM_GRP     = VALUES(ITEM_GRP),
    ITEM_TYPE    = VALUES(ITEM_TYPE),
    DEFAULT_VAL  = VALUES(DEFAULT_VAL),
    UNIT         = VALUES(UNIT),
    CONST_OP     = VALUES(CONST_OP),
    SORT_SEQ     = VALUES(SORT_SEQ),
    DESCRIPTION  = VALUES(DESCRIPTION),
    SOURCE_REF   = VALUES(SOURCE_REF),
    ACTIVE_YN    = VALUES(ACTIVE_YN),
    SELECT_OPTS  = VALUES(SELECT_OPTS),
    LMODAT       = CURDATE();
